version: "3.6"

services:
  openwrt-sdk:
    image: openwrtorg/sdk:${SDKTAG}
    user: 0:0
    env_file: sdkenv.sh
    environment:
      - GROUP_ID=${GROUP_ID}
      - USER_ID=${USER_ID}
    volumes:
      - ./bin:/home/build/openwrt/bin
      - ./sdk:/home/build/sdk
      - ./build-openwrt:/build
      - ${SRC}:/source
    entrypoint:
      - bash 
      - /home/build/sdk/env.sh

  openwrt-sdk-ide:
    build:
      context: .
      dockerfile: Docker-ide-debian
      args:
        dockerimage: openwrtorg/sdk:${SDKTAG}
    network_mode: "host"
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    devices:
      - /dev/dri:/dev/dri
    environment:
      - GROUP_ID=${GROUP_ID}
      - USER_ID=${USER_ID}
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
      - DISPLAY=${DISPLAY}
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./bin:/home/build/openwrt/bin
      - ./config:/home/build/.config
      - ./sdk:/home/build/sdk
      - $HOME:/home/$USER
      - /tmp:/tmp
    entrypoint:
      - bash 
      - /home/build/sdk/env.sh

  openwrt-rootfs:
    image: openwrtorg/rootfs:${ROOTFSTAG}
    ports:
      - "22:22"
    networks:
      - mynet

  openwrt-image-build:
    image: openwrtorg/imagebuilder:${IMAGETAG}

networks:
    mynet:
        driver: bridge
