version: "3.6"

services:
  openwrt-sdk-ide:
    image: openwrt-sdk-ide:ar71xx-generic-18.06.7
    build:
      args:
        dockerimage: openwrtorg/sdk:ar71xx-generic-18.06.7
    #hostname: ar71xx-18_06_7
    entrypoint:
      - bash
      - /home/build/sdk/set-user-env.sh
      - set-toolchain-mips_24kc_gcc-7.3.0_musl-ar71xx-generic-env.sh tmux-startup.sh openwrt-sdk-ide-ar71xx-v19

  openwrt-image-build:
    image: openwrtorg/imagebuilder:ar71xx-generic-18.06.7
    #hostname: build-ar71xx-18_06_7
