ARG downloadimage

FROM debian:latest

RUN apt-get update -qq &&\
    apt-get install -y \
        build-essential \
        curl \
        file \
        gawk \
        gettext \
        git \
        libncurses5-dev \
        libssl-dev \
        python2.7 \
        python3 \
        rsync \
        subversion \
        sudo \
        swig \
        unzip \
        bzip2 \
        wget \
        zlib1g-dev \
        && apt-get -y autoremove \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*

RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
RUN useradd -c "OpenWrt Builder" -m -d /home/build -G sudo -s /bin/bash build
RUN mkdir /home/build/openwrt && \
        cd /tmp && \ 
        wget http://pkg.8devices.com/carambola2/v2.10/OpenWrt-8devices-SDK-v2.10-ar71xx-generic_gcc-5.3.0_musl-1.1.14.Linux-x86_64.tar.bz2 -O openwrt-sdk.tar.bz2 && \
        bunzip2 openwrt-sdk.tar.bz2 && \
        tar xf openwrt-sdk.tar --strip=1 -C /home/build/openwrt && \
        chown build:build /home/build/openwrt/ && \
        rm -rf /tmp/*

USER build
ENV HOME /home/build
WORKDIR /home/build/openwrt/

