version: "3.6"

services:
  openwrt-sdk:
    image: openwrtorg/sdk:${SDKTAG}
    user: 0:0
    env_file: ../sdk/sdkenv.sh
    environment:
      - GROUP_ID=${GROUP_ID}
      - USER_ID=${USER_ID}
    volumes:
      - ../bin:/home/build/openwrt/bin
      - ../sdk:/home/build/sdk
      - ../build-openwrt:/build
      - ${SRC}:/source
    entrypoint:
      - bash 
      - /home/build/sdk/set-user-env.sh
      - set-toolchain-generic-env.sh build-startup.sh