version: "3.6"

services:
  openwrt-sdk-ide:
    image: openwrt-sdk-ide:latest
    build:
      context: .
      dockerfile: Docker-ide-debian
      args:
        dockerimage: openwrtorg/sdk:latest
    network_mode: "host"
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    devices:
      - /dev/dri:/dev/dri
    environment:
      - GROUP_ID
      - USER_ID
      - SSH_AUTH_SOCK
      - DISPLAY
      - PATH
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ../bin:/home/build/openwrt/bin
      - ../config/$DOCKER_CONTAINER:/home/build/.config
      - ../sdk:/home/build/sdk
      - ../build-output:/home/build/build-output
      - ../sources:/home/build/sources
      - $HOME/.Xauthority:/home/build/.Xauthority
      - $HOME:/home/$USER
      - /tmp:/tmp
    entrypoint:
      - bash
      - /home/build/sdk/set-user-env.sh
      - set-toolchain-generic-env.sh tmux-startup.sh openwrt-sdk-ide

  openwrt-rootfs:
    #build:
      #context: .
      #dockerfile: Dockerfile-rootfs
      #args:
        #dockerimage: openwrtorg/rootfs:${ROOTFSTAG}
    image: openwrtorg/rootfs:19.07-SNAPSHOT
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    #network_mode: "host"
    #ports:
      #- "22:22"
    #networks:
      #- mynet

  openwrt-image-build:
    image: openwrt-image-build
    build:
      context: .
      dockerfile: Dockerfile-openwrt
    network_mode: "host"
    user: 0:0
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    devices:
      - /dev/dri:/dev/dri
    environment:
      - GROUP_ID
      - USER_ID
      - SSH_AUTH_SOCK
      - DISPLAY
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - $HOME:/home/$USER
      - ../bin:/home/build/openwrt/bin
      - ../sdk:/home/build/sdk
      - /tmp:/tmp
    entrypoint:
      - bash
      - /home/build/sdk/set-user-env.sh
      - build-startup.sh

#networks:
    #mynet:
        #driver: bridge

#networks:
  #default:
    #driver: bridge
    #ipam:
      #driver: default
      #config:
      #- subnet:  10.103.0.1/16
